name: coming-soon CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t coming-soon .
      - name: Tags
        run: |
          docker tag coming-soon ${{ secrets.DOCKER_USER }}/coming-soon:${{ github.sha }}
          docker tag coming-soon ${{ secrets.DOCKER_USER }}/coming-soon:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/coming-soon:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/coming-soon:latest
